SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'alpine_hut'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'apartment'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'apartments'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'chalet'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'guest_house'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'hostel'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'hotel'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'motel'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'resort'
SELECT DISTINCT name FROM planet_osm_point WHERE tourism = 'wilderness_hut'

SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'bar'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'bar;cafe'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'cafe'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'cafe;coworking_space'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'ice_cream'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'nightclub'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'pub'

SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'bbq'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'biergarten'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'fast_food'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'food_court'
SELECT DISTINCT name FROM planet_osm_point WHERE amenity = 'restaurant'


SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'wilderness_hut'
SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'motel'
SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'hostel'
SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'guest_house'
SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'chalet'
SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'apartment'
SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'hotel'
SELECT DISTINCT name FROM planet_osm_polygon WHERE tourism = 'alpine_hut'

SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'bar'
SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'cafe'
SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'ice_cream'
SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'nightclub'
SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'pub'

SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'biergarten'
SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'fast_food'
SELECT DISTINCT name FROM planet_osm_polygon WHERE amenity = 'restaurant'
